### ISSUE TITLE
Even with errors I always get  "Action Create Bound RPG Program (CRTBNDRPG) for ... was successful"

### ISSUE THREAD

**Issue by SJLennon** [codefori/vscode-ibmi#1677] opened 2023-11-22 20:48 UTC
On PUB400, when I compile an RPG program, I'm always told the complile was successful, even if it failed.

Sample code to recreate the problem:

```
**free
ctl-opt debug  option(*nodebugio: *srcstmt) dftactgrp(*no) actgrp(*caller)
main(Main);
dcl-proc Main;
    // dcl-c FREDMSG 'Hi Fred';
    dsply FREDMSG;
    return;
end-proc;
```

The Code for IBM i output is below.  I wonder if this bit is significant "**qsh: 001-0019 Error found searching for command [[. No such path or directory."**

This is the Code for IBM i output:

/home/LENNONS: /QOpenSys/usr/bin/qsh
liblist -d LENNONS1 LENNONS2 QTEMP QGPL && liblist -c LENNONSB && liblist -a LENNONS1 LENNONSB QGPL QTEMP QIWS && system  "CRTBNDRPG PGM(LENNONS1/AR1E) SRCFILE(LENNONS1/TEMP) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 0,
    "signal": null,
    "stdout": "5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      1\n   Command  . . . . . . . . . . . . :   CRTBNDRPG\n     Issued by  . . . . . . . . . . :     LENNONS\n   Program  . . . . . . . . . . . . :   AR1E\n     Library  . . . . . . . . . . . :     LENNONS1\n   Text 'description' . . . . . . . :   *SRCMBRTXT\n   Source Member  . . . . . . . . . :   AR1E\n   Source File  . . . . . . . . . . :   TEMP\n     Library  . . . . . . . . . . . :     LENNONS1\n     CCSID  . . . . . . . . . . . . :     37\n   Text 'description' . . . . . . . :\n   Last Change  . . . . . . . . . . :   11/22/23  20:41:11\n   Generation severity level  . . . :   10\n   Default activation group . . . . :   *YES\n   Compiler options . . . . . . . . :   *XREF      *GEN       *NOSECLVL  *SHOWCPY\n                                        *EXPDDS    *EXT       *NOSHOWSKP *NOSRCSTMT\n                                        *DEBUGIO   *UNREF     *EVENTF\n   Debugging views  . . . . . . . . :   *SOURCE\n   Debug encryption key . . . . . . :   *NONE\n   Output . . . . . . . . . . . . . :   *PRINT\n   Optimization level . . . . . . . :   *NONE\n   Source listing indentation . . . :   *NONE\n   Type conversion options  . . . . :   *NONE\n   Sort sequence  . . . . . . . . . :   *HEX\n   Language identifier  . . . . . . :   *JOBRUN\n   Replace program  . . . . . . . . :   *YES\n   User profile . . . . . . . . . . :   *USER\n   Authority  . . . . . . . . . . . :   *LIBCRTAUT\n   Truncate numeric . . . . . . . . :   *YES\n   Fix numeric  . . . . . . . . . . :   *NONE\n   Target release . . . . . . . . . :   *CURRENT\n   Allow null values  . . . . . . . :   *NO\n   Define condition names . . . . . :   *NONE\n   Enable performance collection  . :   *PEP\n   Profiling data . . . . . . . . . :   *NOCOL\n   Licensed Internal Code options . :\n   Generate program interface . . . :   *NO\n   Include directory  . . . . . . . :\n   Preprocessor options . . . . . . :   *NONE\n   Require prototype for export . . :   *NO\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      2\n Line   <---------------------- Source Specifications ----------------------------------------------------->  Do  Change Src Seq\n Number ....+....1....+....2....+....3....+....4....+....5....+....6....+....7....+....8....+....9....+...10  Num Date   Id  Number\n                           S o u r c e   L i s t i n g\n      1 **free                                                                                                    000000     000100\n      2 ctl-opt debug  option(*nodebugio: *srcstmt) dftactgrp(*no) actgrp(*caller)                                000000     000200\n 000300 main(Main);                                                                                               000000     000300\n         *--------------------------------------------------------------------*\n         * Compiler Options in Effect:                                        *\n         *--------------------------------------------------------------------*\n         *  Text 'description' . . . . . . . :                                *\n         *  Generation severity level  . . . :   10                           *\n         *  Default activation group . . . . :   *NO                          *\n         *  Compiler options . . . . . . . . :   *XREF      *GEN              *\n         *                                       *NOSECLVL  *SHOWCPY          *\n         *                                       *EXPDDS    *EXT              *\n         *                                       *NOSHOWSKP *SRCSTMT          *\n         *                                       *NODEBUGIO *UNREF            *\n         *                                       *EVENTF                      *\n         *  Optimization level . . . . . . . :   *NONE                        *\n         *  Source listing indentation . . . :   *NONE                        *\n         *  Type conversion options  . . . . :   *NONE                        *\n         *  Sort sequence  . . . . . . . . . :   *HEX                         *\n         *  Language identifier  . . . . . . :   *JOBRUN                      *\n         *  User profile . . . . . . . . . . :   *USER                        *\n         *  Authority  . . . . . . . . . . . :   *LIBCRTAUT                   *\n         *  Truncate numeric . . . . . . . . :   *YES                         *\n         *  Fix numeric  . . . . . . . . . . :   *NONE                        *\n         *  Allow null values  . . . . . . . :   *NO                          *\n         *  Storage model . . .  . . . . . . :   *SNGLVL                      *\n         *  Binding directory from Command . :   *NONE                        *\n         *  Binding directory from Source  . :   *NONE                        *\n         *  Activation group . . . . . . . . :   *CALLER                      *\n         *  Enable performance collection  . :   *PEP                         *\n         *  Profiling data . . . . . . . . . :   *NOCOL                       *\n         *  Generate program interface . . . :   *NO                          *\n         *  Require prototype for export . . :   *NO                          *\n         *--------------------------------------------------------------------*\n 000400 dcl-proc Main;                                                                                            000000     000400\n 000500     // dcl-c FREDMSG 'Hi Fred';                                                                           000000     000500\n 000600     dsply FREDMSG;                                                                                        000000     000600\n 000700     return;                                                                                               000000     000700\n 000800 end-proc;                                                                                                 000000     000800\n        * * * * *   E N D   O F   S O U R C E   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      3\n           A d d i t i o n a l   D i a g n o s t i c   M e s s a g e s\n  Msg id  Sv   Statement    Message text\n *RNF7030 30        000600  The name or indicator FREDMSG is not defined.\n *RNF7503 30        000600  Expression contains an operand that is not defined.\n  * * * * *   E N D   O F   A D D I T I O N A L   D I A G N O S T I C   M E S S A G E S   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      4\n                           C r o s s   R e f e r e n c e\n       File and Record References:\n          File              Device             References (D=Defined)\n            Record\n          No references in the source.\n       Global Field References:\n          Field             Attributes         References (D=Defined M=Modified)\n *RNF7030 FREDMSG           **UNDEF**              000600\n          MAIN              PROTOTYPE              000300      000400\n       Field References for subprocedure MAIN\n          Field             Attributes         References (D=Defined M=Modified)\n          No references in the source.\n       Indicator References:\n          Indicator                            References (D=Defined M=Modified)\n        * * * * *   E N D   O F   C R O S S   R E F E R E N C E   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      5\n                       E x t e r n a l   R e f e r e n c e s\n       Statically bound procedures:\n          Procedure                            References\n          No references in the source.\n       Imported fields:\n          Field             Attributes         Defined\n          No references in the source.\n       Exported fields:\n          Field             Attributes         Defined\n          No references in the source.\n    * * * * *   E N D   O F   E X T E R N A L   R E F E R E N C E S   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      6\n                           M e s s a g e   S u m m a r y\n  Msg id  Sv Number Message text\n *RNF7030 30      1 The name or indicator is not defined.\n *RNF7503 30      1 Expression contains an operand that is not defined.\n        * * * * *   E N D   O F   M E S S A G E   S U M M A R Y   * * * * *\n                                                    -=* http://pub400.com *=-\n  5770WDS V7R5M0  220415 RN        IBM ILE RPG             LENNONS1/AR1E            PUB400     11/22/23 20:42:49        Page      7\n                             F i n a l   S u m m a r y\n   Message Totals:\n     Information  (00) . . . . . . . :        0\n     Warning      (10) . . . . . . . :        0\n     Error        (20) . . . . . . . :        0\n     Severe Error (30+)  . . . . . . :        2\n     ---------------------------------  -------\n     Total . . . . . . . . . . . . . :        2\n   Source Totals:\n     Records . . . . . . . . . . . . :        8\n     Specifications  . . . . . . . . :        4\n     Data records  . . . . . . . . . :        0\n     Comments  . . . . . . . . . . . :        1\n          * * * * *   E N D   O F   F I N A L   S U M M A R Y   * * * * *\n Compilation stopped. Severity 30 errors found in program.\n           * * * * *   E N D   O F   C O M P I L A T I O N   * * * * *\n                                                    -=* http://pub400.com *=-",
    "stderr": "RNS9308:  Compilation stopped. Severity 30 errors found in program.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nRNS9310:  Compilation failed. Program AR1E not created in library LENNONS1.\nqsh: 001-0019 Error found searching for command [[. No such path or directory."
}

/home/LENNONS: system "QSYS/CPYTOIMPF FROMFILE(LENNONS1/EVFEVENT AR1E) TOSTMF('/tmp/lennons/code_for_IBM_i/vscodetemp-O_QSWWePdI') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file EVFEVENT in LENNONS1.",
    "stderr": ""
}

.: rm -f /tmp/lennons/code_for_IBM_i/vscodetemp-O_QSWWePdI
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.4.0|
|Visual Studio Code version|1.84.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.5.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.15.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitLens — Git supercharged (gitlens): 14.5.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
RPGLE (vscode-rpgle): 0.24.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/LENNONS2.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=LENNONSB
CURLIB=LENNONSB
HOME=/home/LENNONS
HOST=pub400.com
IFS_LIB=LENNONSB
IFS_SRCPF=VSCODE
LIB1=LENNONSB
LIBLS=LENNONS1 LENNONSB QGPL QTEMP QIWS
LOGIN=lennons
LOGNAME=lennons
MAIL=/var/spool/mail/lennons
OLDPWD=/home/LENNONS
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin/:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LENNONS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=71.63.120.199 55530 2222
SSH_CONNECTION=71.63.120.199 55530 185.113.5.134 2222
TZ=<UTC>0
USER=lennons
USERNAME=lennons
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(LENNONS2) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "system \"DLTOBJ OBJ(LENNONS2/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "ls -p /home/lennons/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/home/lennons/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/LENNONS"
  }
]
```
</details>

**Comment by worksofliam** [comment] 2023-11-23 17:23
This is still the same issue as before:

```
qsh: 001-0019 Error found searching for command [[. No such path or directory
```

**Comment by worksofliam** [comment] 2023-11-23 17:23
Closing as dupe of #1535.

**Closed** 2023-11-23 17:23 UTC
