### ISSUE TITLE
What's the best approach on deployment

### ISSUE THREAD

**Issue by vaisoliviu** [codefori/vscode-ibmi#1957] opened 2024-03-26 16:16 UTC
### Discussed in https://github.com/orgs/codefori/discussions/1956

<div type='discussions-op-text'>

<sup>Originally posted by **vaisoliviu** March 26, 2024</sup>
Hello guys,

I have some question related to the deployment and build directly on the IFS.

I am currently using Codefori for some time, and I love it.
Found some of Liam's videos where he explains the use of Git and deployment+build on the IFS, and decided to give it a try.

I am currently developing on the AS400 machine, on an IASP. In order to have access to the IASP in VSCode I modified the JOBD for my user to set this IASP as the default. I have the sources in a number of libraries, depending on the client, but they are all same IASP.

I would love to be able to write the code locally and deploy it and compile it on the IFS, but it doesn't work for now for me 😞.
I copied all the sources to a local folder, and set up the deployment to the IFS as shown by Liam, but when I try to compile i get some errors.
Then I was thinking, what if the program that I am compiling needs a file or another object in order to be able to compile?
I did not create a make file, i'm not sure if I need one or not, I remember seeing a tutorial where it worked without it ???

Could u give me a hint to the best solution i could use?

</div>

**Comment by worksofliam** [comment] 2024-03-26 16:27
Closing as dupe of discussion.

**Closed by worksofliam** 2024-03-26 16:27 UTC
