### ISSUE TITLE
Trying to opening a filer getting "Invalid time value" error

### ISSUE THREAD

**Issue by sureshramakrishnan** [codefori/vscode-ibmi#2050] opened 2024-05-13 20:55 UTC
👉🏻I defined a simple filter for source in a library in protected with object explorer as this is production code/source...when I click to open the filter to see the list of source. I am getting an "Invalid time value"

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.10.1|
|Visual Studio Code version|1.89.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.4.11
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Db2 for IBM i (vscode-db2i): 1.0.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.17.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Debug (ibmidebug): 1.0.0
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|13|
|CCSID Origin|system|
|Runtime CCSID|65535|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QOpenSys/pkgs/bin|/QSYS.lib/ILEDITOR.lib||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|-|
|attr|bash|GETNEWLIBL.PGM|ILEDITOR.GETMBRINFO|QZDFMDB2.PGM|startDebugService.sh|
|iconv||||||
|ls||||||
|setccsid||||||
|tar||||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"sramakrish\" && export HOST=\"192.168.9.10\" && export HOME=\"/home/SRAMAKRISH\" && export WORKDIR=\"/home/SRAMAKRISH\" && export LIBLS=\"ESEND DBU11 IPTSUTL IPTSPGM SEQUEL SEQUELWI QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/SRAMAKRISH"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"sramakrish\" && export HOST=\"192.168.9.10\" && export HOME=\"/home/SRAMAKRISH\" && export WORKDIR=\"/home/SRAMAKRISH\" && export LIBLS=\"ESEND DBU11 IPTSUTL IPTSPGM SEQUEL SEQUELWI QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/SRAMAKRISH"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"sramakrish\" && export HOST=\"192.168.9.10\" && export HOME=\"/home/SRAMAKRISH\" && export WORKDIR=\"/home/SRAMAKRISH\" && export LIBLS=\"ESEND DBU11 IPTSUTL IPTSPGM SEQUEL SEQUELWI QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/SRAMAKRISH"
  }
]
```
</details>

**Comment by worksofliam** [comment] 2024-05-13 21:01
Please share the contents of your Code for IBM i output channel after you see the error.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

I believe this might be a possible dupe of #1813

**Comment by sureshramakrishnan** [comment] 2024-05-13 22:03
The output is empty...Please see the attached. I will check the issue 1813.
![image](https://github.com/codefori/vscode-ibmi/assets/74662197/fafb510b-a486-40bf-bae2-a38fe03e1a80)
![Screenshot 2024-05-13 150055](https://github.com/codefori/vscode-ibmi/assets/74662197/7d6e4c07-2135-4751-85a3-34460227fb8d)

**Comment by sureshramakrishnan** [comment] 2024-05-13 22:24
Please see the attached recording...
https://github.com/codefori/vscode-ibmi/assets/74662197/bd423385-6bd6-4861-a04f-2f1b6e757937

**Comment by SJLennon** [comment] 2024-05-14 00:18
@sureshramakrishnan 
To populate the output, you need to select Code for IBM i in the dropdown.
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/d4bdae79-ccf1-4741-9fa5-1e8cf3de6365)

**Comment by sureshramakrishnan** [comment] 2024-05-14 03:23
Thanks for the note...Please see the below from OUTPUT...

/home/SRAMAKRISH: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(37)');
select 
  t.SYSTEM_TABLE_NAME as NAME,
  '*FILE'             as TYPE,
  'PF'                as ATTRIBUTE,
  t.TABLE_TEXT        as TEXT,
  1                   as IS_SOURCE,
  t.ROW_LENGTH        as SOURCE_LENGTH
from QSYS2.SYSTABLES as t
where t.table_schema = 'IPTSPCH191' and t.file_type = 'S';
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nNAME       TYPE  ATTRIBUTE  TEXT                                               IS_SOURCE   SOURCE_LENGTH \n---------- ----- ---------- -------------------------------------------------- ----------- --------------\nQCLSRC     *FILE PF         19.1 CLP/CLLE Source, �Island Pacific                        1             92\nQCMDSRC    *FILE PF         19.1 CMD Source, �Island Pacific                             1             92\nQSRVSRC    *FILE PF         19.1 SRV Source, �Island Pacific                             1             92\nQSQLSRC    *FILE PF         19.1 SQL Source, �Island Pacific                             1             92\nQRPGSRC    *FILE PF         19.1 RPG Source, �Island Pacific                             1             92\nQCSRC      *FILE PF         19.1 C Source, �Island Pacific                               1            112\nQDDSSRC    *FILE PF         19.1 DDS Source, �Island Pacific                             1             92\nQFMTSRC    *FILE PF         19.1 FMT Source, �Island Pacific                             1             92\nQPNLSRC    *FILE PF         19.1 PNLGRP Source, �Island Pacific                          1            112\nQRPGLESRC  *FILE PF         19.1 RPGLE Source, �Island Pacific                           1            112\n\n 10 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

**Comment by worksofliam** [comment] 2024-05-14 12:49
@sureshramakrishnan We need the entire output. Please share the other content you didn't before.

**Comment by Augustodunensis** [comment] 2024-05-15 09:38
I also face this issue on V7R2M0. The problem is occurring since 2.10.1 and is connected with change in [api/IBMiContent.ts](https://github.com/codefori/vscode-ibmi/commit/75bbd0fcb5a6ea6cc61fafa45e15402e60b155ae#diff-e1962db673dbf505e2c74deb034072677a2b4fca832d78a983eebeecac55df85) 
Since, up to R2, QSYS2.OBJECT_STATISTICS has no column named CHANGE_TIMESTAMP, the sql query returns an error. 
The other problem is - when date is incorrect, there is also no escaping, so it also leads to an error.

**Comment by sureshramakrishnan** [comment] 2024-05-15 16:37
Hi,This partition is  V7R3 and I do see CHANGE_TIMESTAMP in QSYS2.OBJECT_STATISTICS



    On Wednesday, May 15, 2024 at 02:38:43 AM PDT, Augusto Dunensis ***@***.***> wrote:  
 
 


I also face this issue on V7R2M0. The problem is occurring since 2.10.1 and is connected with change in api/IBMiContent.ts
Since, up to R2, QSYS2.OBJECT_STATISTICS has no column named CHANGE_TIMESTAMP, the sql query returns an error.
The other problem is - when date is incorrect, there is also no escaping, so it also leads to an error.

**Comment by sureshramakrishnan** [comment] 2024-05-16 20:28
Object browser bring list when type is *ALL. Setting *ALL and name as Q* get the list of Source file but they are showing up as PF's
![image](https://github.com/codefori/vscode-ibmi/assets/74662197/a8ff51f0-f1f1-484a-88bc-34d8b9bbaa11)

**Comment by sureshramakrishnan** [comment] 2024-05-23 17:25
I have set it as *SRCPF please see the screen print


    On Wednesday, May 22, 2024 at 06:33:54 AM PDT, LJ ***@***.***> wrote:  
 
 


@sureshramakrishnan you can change your PF filter object type to *SRCPF

**Comment by onlysumitg** [comment] 2024-05-23 19:34
Try removing any special character from the source file description.

**Comment by sureshramakrishnan** [comment] 2024-05-24 04:37
Hi I have tried the same but still getting errors...


    On Thursday, May 23, 2024 at 12:35:06 PM PDT, Sumit goyal ***@***.***> wrote:  
 
 


Try removing any special character from the source file description.

**Comment by onlysumitg** [comment] 2024-05-24 15:02
@sureshramakrishnan 
If you would like, I can help you troubleshoot the issue. We can connect over a zoom call.

**Comment by SJLennon** [comment] 2024-05-24 15:36
@sureshramakrishnan 

For what it's worth, just in case any of this helps...

You said:

> I have set it as *SRCPF please see the screen print

Your screen shot shows differently:
![image](https://github.com/codefori/vscode-ibmi/assets/67484051/5897ddc2-43e4-4934-9d70-a4ec37b86d12)
You might want to change the "Object types" to *SRCPF.

Of course, if the screen shot was wrong and you have *SRCPF set, then you might want to look at the CCSID section in the documentation, since it does seem like there are some "odd" characters showing up:

![image](https://github.com/codefori/vscode-ibmi/assets/67484051/786f9a22-04bd-4373-aecf-4f983ac7412a)

And actually, from reading all the comments, and the issue title, I'm not sure if you now have one issue ("Invalid time error") or also a second issue, ("list of Source file but they are showing up as PF's")

**Comment by chrjorgensen** [comment] 2024-05-29 07:23
@sureshramakrishnan Please enter any findings / solution here in the issue - for others to learn about how this was resolved. 🙏

**Closed** 2024-09-03 01:38 UTC
Labels: info-needed
