### ISSUE TITLE
Wildcard library filter in Object Browser not working

### ISSUE THREAD

**Issue by tom-writes-code** [codefori/vscode-ibmi#2304] opened 2024-10-22 09:17 UTC
Type: <b>Bug</b>

Create a filter with the following properties:
Type: simple
Libraries: use a wildcard, e.g. o#12345* for all libraries starting o#12345
Objects: *
Object types: *SRCPF
Members: *
Member type: *
Not protected

The object browser is able to expand the list of libraries picked up, but no source can be seen in the libraries.

![image](https://github.com/user-attachments/assets/4e5479d0-ee83-4179-b0cc-053203ac6ea8)

Previously, this would further break down into source types, but that is no longer possible when wildcarding.

Extension version: 2.13.5
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.74GB free)|
|Process Argv|--crash-reporter-id 8ca305ff-1eb7-4e9b-88dc-b5695f2c805a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31162478
icondisabled:31158250

```

</details>

**Comment by sebjulliand** [comment] 2024-10-23 00:35
Please copy/paste the content of the Code for IBM i output after the browser fails to list the source files.
Also, what's your system/user CCSID?

**Comment by tom-writes-code** [comment] 2024-10-23 07:39
Hiya - sorry, I've only just found the "how to report a bug" section on the documentation.

👉🏻 Issue text goes here.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.13.5|
|Visual Studio Code version|1.94.2|
|Operating System|win32_x64|


<details>
<summary>Active extensions</summary>

```
.NET Install Tool (vscode-dotnet-runtime): 2.2.1
COBOL (cobol): 24.10.22
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.6.1
Dev Containers (remote-containers): 0.388.0
ESLint (vscode-eslint): 3.0.10
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.20.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 15.6.2
IBM i Debug (ibmidebug): 2.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.11.1
IIS and IIS Express extension for Visual Studio Code (iis): 1.0.14
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.10
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Postman (postman-for-vscode): 1.3.0
Prettier - Code formatter (prettier-vscode): 11.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.88.4
YAML (vscode-yaml): 1.15.0
gitignore (help-me-add): 1.0.1
vscode-openapi-viewer (vscode-openapi-viewer): 1.1.4
```
</details>


<hr />


<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|3|
|CCSID Origin|65535|
|Runtime CCSID|65535|
|Default CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|/QOpenSys/QIBM/ProdData/JavaVM/jdk80|/QOpenSys/QIBM/ProdData/JavaVM/jdk11|/QOpensys/pkgs/lib/jvm|
|-|-|-|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|64bit|64bit|openjdk-11|
|chsh|iconv|||||||
|find|setccsid|||||||
|git||||||||
|grep||||||||
|ls||||||||
|md5sum||||||||
|sort||||||||
|stat||||||||
|tar||||||||
|tn5250||||||||
</details>



<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=
LANG=en_GB.utf8
LC_ALL=EN_GB
LIBLS=QGPL2 QGPL QTEMP
LOGIN=
LOGNAME=
MAIL=
OLDPWD=
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:usr/sbin:.:/usr/bin
PWD=
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=
SSH_CONNECTION=
TZ=<GMT>0<BST>,M3.5.0,M10.5.0
USER=
USERNAME=
WORKDIR=
_=/QOpenSys/pkgs/bin/env
```
</details>



<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>



<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/usr/bin/attr -p /QSYS.LIB/O#06287536.FILE CCSID",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/O#06287536.FILE.  No such path or directory.",
    "cwd": "/home/<username>"
  },
  {
    "command": "cd \"/QSYS.LIB/O#06287525.FILE\" && (ls | wc -l)",
    "code": 1,
    "stderr": "bash: line 1: cd: /QSYS.LIB/O#06287525.FILE: No such file or directory",
    "cwd": "/home/<username>"
  },
  {
    "command": "/usr/bin/attr -p /QSYS.LIB/O#06287525.FILE CCSID",
    "code": 1,
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/O#06287525.FILE.  No such path or directory.",
    "cwd": "/home/<username>"
  }
]
```
</details>

**Comment by worksofliam** [comment] 2024-10-28 15:49
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by worksofliam** [comment] 2024-10-29 14:46
What happens if you run this SQL statement via VS Code or ACS?

```sql
With MEMBERS As (         SELECT           rtrim(cast(a.system_table_schema as char(10) )) as LIBRARY,           b.avgrowsize as RECORD_LENGTH,           a.iasp_number as ASP,           rtrim(cast(a.system_table_name as char(10) )) AS SOURCE_FILE,           rtrim(cast(b.system_table_member as char(10) )) as NAME,           coalesce(rtrim(cast(b.source_type as varchar(10) )), '') as TYPE,           coalesce(rtrim(varchar(b.partition_text)), '') as TEXT,           b.NUMBER_ROWS as LINES,           extract(epoch from (b.CREATE_TIMESTAMP))*1000 as CREATED,           extract(epoch from (b.LAST_SOURCE_UPDATE_TIMESTAMP))*1000 as CHANGED         FROM qsys2.systables AS a           JOIN qsys2.syspartitionstat AS b             ON b.table_schema = a.table_schema AND               b.table_name = a.table_name       )       Select * From MEMBERS       Where LIBRARY = 'QSYS'         And SOURCE_FILE = 'O#06287525'         And NAME Like '%'         And TYPE Like '%'       Order By NAME ASC
```

**Comment by tom-writes-code** [comment] 2024-10-29 15:00
![image](https://github.com/user-attachments/assets/df2c97a0-3c19-49e7-a7a1-dceb73b6cedd)

0 rows retrieved.

I feel like it's assuming that `o#06287525` is a source file, rather than a library. e.g, if it was looking for source file QRPGLESRC in library O#06287525, then it does find rows.

**Comment by SJLennon** [comment] 2024-10-29 16:36
FWIW: Here's the code re-formatted with iACS:
```
WITH MEMBERS AS (
SELECT RTRIM(CAST(a.system_table_schema AS CHAR(10))) AS LIBRARY
       ,b.avgrowsize AS RECORD_LENGTH
       ,a.iasp_number AS ASP
       ,RTRIM(CAST(a.system_table_name AS CHAR(10))) AS SOURCE_FILE
       ,RTRIM(CAST(b.system_table_member AS CHAR(10))) AS NAME
       ,COALESCE(RTRIM(CAST(b.source_type AS VARCHAR(10))), '') AS TYPE
       ,COALESCE(RTRIM(VARCHAR(b.partition_text)), '') AS TEXT
       ,b.NUMBER_ROWS AS LINES
       ,EXTRACT(EPOCH FROM (b.CREATE_TIMESTAMP)) * 1000 AS CREATED
       ,EXTRACT(EPOCH FROM (b.LAST_SOURCE_UPDATE_TIMESTAMP)) * 1000 AS CHANGED
FROM qsys2.systables AS a
     JOIN qsys2.syspartitionstat AS b
     ON b.table_schema = a.table_schema
     AND b.table_name = a.table_name
)
SELECT *
FROM MEMBERS
WHERE LIBRARY = 'QSYS'
      AND SOURCE_FILE = 'O#06287525'
      AND NAME LIKE '%'
      AND TYPE LIKE '%'
ORDER BY NAME ASC;
```

**Comment by worksofliam** [comment] 2024-10-29 17:59
@sebjulliand Is this logic defined in the `getMemberList` API?

**Comment by worksofliam** [comment] 2024-10-30 20:22
@tom-writes-code If you use a specific library name, does it work? Think I am closing in on a fix.

**Comment by tom-writes-code** [comment] 2024-10-30 20:24
Hi

Yep - if I specify the full library in the filter, e.g. o#06287525 then the filter works

**Comment by worksofliam** [comment] 2024-10-30 20:36
Here is my filter which I have setup as you described.

<img width="747" alt="image" src="https://github.com/user-attachments/assets/b3e64b63-725b-4a74-8edf-b945da0972b8">

Here is the results, which makes a lot more sense:

<img width="343" alt="image" src="https://github.com/user-attachments/assets/7d419bf6-7989-4ac9-a69e-d384684f333d">

**Comment by worksofliam** [comment] 2024-10-30 20:37
@tom-writes-code I wonder if this is something dumb. Any chance you can create a wildcard filter for libraries that don't contain the pound sign / hash tag? (`#`)

**Comment by tom-writes-code** [comment] 2024-10-31 08:59
Same outcome I'm afraid

![image](https://github.com/user-attachments/assets/876eadd0-d05e-4a0e-8a9a-efed2b3fc4aa)

![image](https://github.com/user-attachments/assets/24a08248-66ed-41ed-8831-7056967160d7)

![image](https://github.com/user-attachments/assets/5d8e6714-ef51-40d5-920b-6751d70c9df0)

```
[...]
/home/SHARPT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(37)');
CREATE TABLE QTEMP.O_BBRRZ AS (select    OBJNAME          as NAME,   OBJTYPE          as TYPE,   OBJATTRIBUTE     as ATTRIBUTE,   OBJTEXT          as TEXT,   0                as IS_SOURCE,   IASP_NUMBER      as IASP_NUMBER,   OBJSIZE          as SIZE,   extract(epoch from (OBJCREATED))*1000       as CREATED,   extract(epoch from (CHANGE_TIMESTAMP))*1000 as CHANGED,   OBJOWNER         as OWNER,   OBJDEFINER       as CREATED_BY from table(QSYS2.OBJECT_STATISTICS(OBJECT_SCHEMA => 'QSYS      ', OBJTYPELIST => '*LIB', OBJECT_NAME => 'SNDBX*'))) WITH DATA;
Call QSYS2.QCMDEXC('CPYTOIMPF FROMFILE(QTEMP/O_BBRRZ *FIRST) TOSTMF(''/tmp/vscodetemp-O_leKCk6DX'') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM('','') DECPNT(*PERIOD)')
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/SHARPT: rm -rf "/tmp/vscodetemp-O_MPRFPRtG"
/home/SHARPT: ls $HOME/.vscode/mapepire-server-2.1.4.jar
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "/home/SHARPT/.vscode/mapepire-server-2.1.4.jar",
    "stderr": ""
}

/home/SHARPT: echo $SHELL
/home/SHARPT: rm -rf "/tmp/vscodetemp-O_leKCk6DX"
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/SHARPT: /QOpenSys/usr/bin/qsh
system  "CHKOBJ OBJ(QSYS/SNDBX1) OBJTYPE(*FILE) AUT(*UPD)"
/home/SHARPT: cd "/QSYS.LIB/SNDBX1.FILE" && (ls | wc -l)
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "bash: line 1: cd: /QSYS.LIB/SNDBX1.FILE: No such file or directory"
}

/home/SHARPT: /usr/bin/attr -p /QSYS.LIB/SNDBX1.FILE CCSID
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801:  Object SNDBX1 in library QSYS not found.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed."
}

/home/SHARPT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
Call QSYS2.QCMDEXC('CHGJOB CCSID(37)');
CREATE TABLE QTEMP.O_4YXFM AS (With MEMBERS As (         SELECT           rtrim(cast(a.system_table_schema as char(10) )) as LIBRARY,           b.avgrowsize as RECORD_LENGTH,           a.iasp_number as ASP,           rtrim(cast(a.system_table_name as char(10) )) AS SOURCE_FILE,           rtrim(cast(b.system_table_member as char(10) )) as NAME,           coalesce(rtrim(cast(b.source_type as varchar(10) )), '') as TYPE,           coalesce(rtrim(varchar(b.partition_text)), '') as TEXT,           b.NUMBER_ROWS as LINES,           extract(epoch from (b.CREATE_TIMESTAMP))*1000 as CREATED,           extract(epoch from (b.LAST_SOURCE_UPDATE_TIMESTAMP))*1000 as CHANGED         FROM qsys2.systables AS a           JOIN qsys2.syspartitionstat AS b             ON b.table_schema = a.table_schema AND               b.table_name = a.table_name       )       Select * From MEMBERS       Where LIBRARY = 'QSYS'         And SOURCE_FILE = 'SNDBX1'         And NAME Like '%'         And TYPE Like '%'       Order By NAME ASC) WITH DATA;
Call QSYS2.QCMDEXC('CPYTOIMPF FROMFILE(QTEMP/O_4YXFM *FIRST) TOSTMF(''/tmp/vscodetemp-O_GJ7ZBF9F'') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM('','') DECPNT(*PERIOD)')
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/SNDBX1.FILE.  No such path or directory."
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.\nDB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/SHARPT: cd "/QSYS.LIB/SNDBX2.FILE" && (ls | wc -l)
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "bash: line 1: cd: /QSYS.LIB/SNDBX2.FILE: No such file or directory"
}

/home/SHARPT: /usr/bin/attr -p /QSYS.LIB/SNDBX2.FILE CCSID
/home/SHARPT: rm -rf "/tmp/vscodetemp-O_GJ7ZBF9F"
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "attr: 001-2248 Error found getting attributes for file /QSYS.LIB/SNDBX2.FILE.  No such path or directory."
}

{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```

**Comment by sebjulliand** [comment] 2024-11-03 18:29
That's odd...it lists the libraries but give them the `*FILE` type instead of `*LIB`.

@tom-writes-code , would you mind running this query and putting the result here?
```sql
select
      OBJNAME as NAME,
      OBJTYPE as type,
      OBJATTRIBUTE as ATTRIBUTE,
      OBJTEXT as TEXT,
      0 as IS_SOURCE,
      IASP_NUMBER as IASP_NUMBER,
      OBJSIZE as SIZE,
      extract(
        epoch
        from
          (OBJCREATED)
      ) * 1000 as CREATED,
      extract(
        epoch
        from
          (CHANGE_TIMESTAMP)
      ) * 1000 as CHANGED,
      OBJOWNER as OWNER,
      OBJDEFINER as CREATED_BY
    from
      table (
        QSYS2.OBJECT_STATISTICS (
          OBJECT_SCHEMA => 'QSYS      ',
          OBJTYPELIST => '*LIB',
          OBJECT_NAME => 'SNDBX*'
        )
      )
```

Thanks!

**Comment by tom-writes-code** [comment] 2024-11-04 09:55
Hi Seb - no problem. Two rows retrieved:

![image](https://github.com/user-attachments/assets/cd51619d-623d-499d-96ce-4597755dd1a9)

**Comment by Augustodunensis** [comment] 2024-11-13 10:16
I confirm this issue on V7R3M0. The unexpected behavior is occuring since version 2.13.4, on 2.13.3 is working fine.

**Closed** 2024-11-26 14:25 UTC
Labels: info-needed

**Comment by worksofliam** [comment] 2024-11-26 14:34
We believe to have solved this issue. You can switch to the pre-release to try the fix.

**Comment by tom-writes-code** [comment] 2024-11-26 15:05
Yep, this is working for me on V2.14.0, thanks everyone!
