### ISSUE TITLE
VS Code / Code for IBM i - getting started - connecting to system

### ISSUE THREAD

**Issue by eaglerockdude** [codefori/vscode-ibmi#1581] opened 2023-10-09 00:55 UTC
### Discussed in https://github.com/orgs/codefori/discussions/1552

<div type='discussions-op-text'>

<sup>Originally posted by **wood3875** September 26, 2023</sup>
Help ?

I'm simply trying to connect with userid/password and VS Code is complaining:  **config.privateKeyPath does not exist at given fs path.**  Tried host name, IP, and FQDN - same result.  I'm NOT using a key pair...  VS Code came from employer software center, and then added Code for IBM i extension, that's it.

Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

A co-worker suggested proxy, but I don't need/use that for any other system connection.

</div>

**Comment by worksofliam** [comment] 2023-10-13 20:29
Closing as dupe of discussion.

**Closed** 2023-10-13 20:33 UTC
