### ISSUE TITLE
Cannot connect to IBM i

### ISSUE THREAD

**Issue by pranab101** [codefori/vscode-ibmi#2265] opened 2024-09-20 14:39 UTC
I cannot connect to IBM i through VS Code. I have all correct credentials but I still get an error 

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.13.0|
|Visual Studio Code version|1.93.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.5.0
Configuration Editing (configuration-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 1.5.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by sebjulliand** [comment] 2024-09-20 15:08
Duplicate of https://github.com/codefori/vscode-ibmi/issues/2262
No need to open multiple issues; keep the conversation in one place. Thanks!

**Comment by sebjulliand** [comment] 2024-09-20 15:08
No need to open multiple issues; keep the conversation in one place. Thanks!

**Closed by sebjulliand** 2024-09-20 15:08 UTC
